### PR TITLE
Atpv3 implement cancel

### PR DESCRIPTION
**Pull request by dustinblack**
## Changes introduced with this PR

Bump the plugin to SDK 0.13.0 and ATP v3. Remove artificial timeout and replace it with a cancel signal. Add ability to cancel via keyboard (ctrl-c) and continue post processing and results dump for stand-alone plugin use.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by BATMAN-JD — APPROVED** [review]

**Comment by BATMAN-JD** [comment]
oh wow strange. The files changed was only the README....now approved I see the rest. I will look at this after the build.

**Comment by dustinblack** [comment]
@jaredoconnell It looks like the change in approach to capturing the keyboard interrupt still results in the same problem when run within a workflow:
```
2023-11-02T12:45:49+01:00	debug	source=plugin-provider	Step start-pcp started, waiting for response...
2023-11-02T12:45:49+01:00	error	source=plugin-provider	Step with run ID pcp sent error message: {Error while calling step pcp/start-pcp:signal only works in main thread of the main interpreter Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/arcaflow_plugin_sdk/atp.py", line 285, in start_step
    output_id, output_data = self.plugin_schema.call_step(
  File "/usr/local/lib/python3.9/site-packages/arcaflow_plugin_sdk/schema.py", line 5803, in call_step
    return self._call_step(self.get_step(step_id), run_id, input_param)
  File "/usr/local/lib/python3.9/site-packages/arcaflow_plugin_sdk/schema.py", line 5835, in _call_step
    return step(
  File "/usr/local/lib/python3.9/site-packages/arcaflow_plugin_sdk/schema.py", line 5681, in __call__
    step_local_data: _StepLocalData = self.setup_run_data(run_id)
  File "/usr/local/lib/python3.9/site-packages/arcaflow_plugin_sdk/schema.py", line 5661, in setup_run_data
    new_run_data = _StepLocalData(self._step_object_constructor())
  File "/app/arcaflow_plugin_pcp/pcp_plugin.py", line 59, in <lambda>
    step_object_constructor=lambda: StartPcpStep(),
  File "/app/arcaflow_plugin_pcp/pcp_plugin.py", line 29, in __init__
    signal.signal(signal.SIGINT, self.ctrl_c_handler)
  File "/usr/lib64/python3.9/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
 true false}
```

**Review by jaredoconnell — COMMENTED** [review]
Is the timeout just a different implementation of run_duration for when the plugin isn't cancelled?

**Comment by dustinblack** [comment]
> Is the timeout just a different implementation of run_duration for when the plugin isn't cancelled?

Yes. Initially I got rid of the run_duration entirely, but it creates complications in testing if there isn't a way to time out the plugin execution, and I decided that there could be other use cases for having a timeout, so I re-implemented it using the `Event().wait()` functionality.

**Review by jaredoconnell — APPROVED** [review]
Seems like a good way to design it given the current SDK.

**Review by mfleader — APPROVED** [review]

**Pull request merged**
